In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

The resulting dataset is a Bunch object:

In [4]:
 type(iris)

sklearn.utils._bunch.Bunch

 You can see what's available for this data type by using the method iris.keys():


In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

A Bunch object is similar to a dicitionary, but it additionally allows accessing the keys in an attribute style:

In [6]:
print(iris["target_names"])
print(iris.target_names)

['setosa' 'versicolor' 'virginica']
['setosa' 'versicolor' 'virginica']


 The features of each sample flower are stored in the
 **data** attribute of the dataset:

In [10]:
 n_samples, n_features = iris.data.shape
 print('Number of samples:', n_samples)
 print('Number of features:', n_features)
 # the sepal length, sepal width, petal length and petal width of the first sample (first flower)
 print(iris.data[0])

Number of samples: 150
Number of features: 4
[5.1 3.5 1.4 0.2]


The feautures of each flower are stored in the **data** attribute of the data set. Let's take a look at some of the samples:



In [11]:
# Flowers with the indices 12, 26, 89, and 114
iris.data[[12, 26, 89, 114]]

array([[4.8, 3. , 1.4, 0.1],
       [5. , 3.4, 1.6, 0.4],
       [5.5, 2.5, 4. , 1.3],
       [5.8, 2.8, 5.1, 2.4]])

 The information about the class of each sample, i.e. the labels, is stored in the "target" attribute of the data set

In [12]:
print(iris.data.shape)
print(iris.target.shape)

(150, 4)
(150,)


In [13]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


 Using NumPy's bincount function (above) we can see that the classes in this dataset are evenly distributed
there are 50 flowers of each species, with
 • class 0: Iris Setosa
 • class 1: Iris Versicolor
 • class 2: Iris Virginica

In [14]:
import numpy as np

np.bincount(iris.target)

array([50, 50, 50])

These class names are stored in the last attribute, namely **target_names** :

In [15]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']
